version: '3.8'

volumes:
  db_blog:
  wordpress_vol:

networks:
  wordpress_net:
    driver: bridge

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: Mysql12#
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
    ports:
      - 3306:3306
    volumes:
      - db_blog:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:6.4.3
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - wordpress_net
